# Generated by Django 5.2.4 on 2025-09-13 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Nuts', 'Nuts'), ('Sesame', 'Sesame'), ('Diary', 'Diary product (milk)'), ('Eggs', 'Eggs'), ('Gluten', 'Gluten (containing Wheat, Rye etc)'), ('Soy', 'Soy'), ('Fish', 'Fish'), ('Shellfish', 'Shellfish'), ('Celery', 'Celery'), ('Mustard', 'Mustard'), ('Sulfur dioxide', 'Sulfur dioxide'), ('Other', 'Add your allergy')], default=None, max_length=15)),
                ('other_allergy', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoB', models.DateField()),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='images/profile_pics')),
                ('allergies', models.ManyToManyField(blank=True, to='lunch_box_app.allergy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
