# Generated by Django 5.2.6 on 2025-09-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_box_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(choices=[('Nuts', 'Nuts'), ('Sesame', 'Sesame'), ('Diary', 'Diary product (milk)'), ('Eggs', 'Eggs'), ('Gluten', 'Gluten (containing Wheat, Rye etc)'), ('Soy', 'Soy'), ('Fish', 'Fish'), ('Shellfish', 'Shellfish'), ('Celery', 'Celery'), ('Mustard', 'Mustard'), ('Sulfur dioxide', 'Sulfur dioxide'), ('Other', 'Add your allergy')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='lunch_box_app.allergy'),
        ),
    ]
