# Generated by Django 5.2.6 on 2025-09-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_box_app', '0002_alter_allergy_name_alter_userprofile_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='lunch_box_app.allergy'),
        ),
    ]
